num_frames: 16
sample_stride: 1
data_stride: 16
data_mode: joint3d

load_data_file: "/data1/wxs/DATASETS/PW3D_ByBradley/all_data.pkl"
load_image_source_file: "/data1/wxs/DATASETS/PW3D_ByBradley/images_source.pkl"
load_bbox_file: "/data1/wxs/DATASETS/PW3D_ByBradley/bboxes_xyxy.pkl"
load_text_source_file: ''
return_extra: [[image]]

# data preprocessing config
normalize: anisotropic

# image config
filter_invalid_images: True
processed_image_shape: [448,448]
backbone: hrnet_32

# dataloader config
get_item_list: [factor_2_5d,
                video_rgb, joint3d_image_affined, joint3d_image_affined_normed, joint3d_image_affined_scale, joint3d_image_affined_transl,
                'affine_trans', 'affine_trans_inv',
                'joint_2_5d_image']